server:
  port: 8000
management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: uim
#  cloud:
#    nacos:
#      discovery:
#        server-addr: nacos.kevin.com:80
#        username: nacos
#        password: 888888
  datasource:
    url: jdbc:postgresql://172.25.48.1:5432/sampleuser
    username: postgres
    password: postgres
  data:
    redis:
      database: 0
      host: 172.25.48.1
      port: 6379
      jedis:
        pool:
          max-active: 20
          max-idle: 20
          max-wait: 10
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://uim.kevin.com
          jwk-set-uri: http://uim.kevin.com/oauth2/jwks
#  zipkin:
#    base-url: http://zipkin.kevin.com:80

mybatis:
  configuration:
    map-underscore-to-caml-case: true

logging:
  level:
    com.kevin.sample.uim.mapper: debug
    org.springframework.security: DEBUG