---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kevin.
--- DateTime: 2023/8/26 14:48
---

local inventoryId = KEYS[1]
local total = KEYS[2]
local sale = KEYS[3]

redis.call('hset', inventoryId, 'total', total)
redis.call('hset', inventoryId, 'sale', sale)

local result = {}
result.inventoryId = inventoryId
result.total = total
result.sale = sale

local ret = cjson.encode(result)
return ret