server:
  port: 7000
spring:
  application:
    name: order
  cloud:
    nacos:
      discovery:
        server-addr: nacos.kevin.com:80
        username: nacos
        password: 888888
  shardingsphere:
    mode:
      type: Memory
    props:
      show-sql: true
    datasource:
      names: ds0,ds1
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://localhost:5432/ds0
        username: postgres
        password: postgres
        connectionTimeoutMilliseconds: 30000
        idleTimeoutMilliseconds: 60000
        maxLifetimeMilliseconds: 1800000
        maxPoolSize: 50
        minPoolSize: 1
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://localhost:5432/ds1
        username: postgres
        password: postgres
        connectionTimeoutMilliseconds: 30000
        idleTimeoutMilliseconds: 60000
        maxLifetimeMilliseconds: 1800000
        maxPoolSize: 50
        minPoolSize: 1
    rules:
      sharding:
        tables:
          t_order:
            actual-data-nodes: ds${0..1}.t_order${0..1}
            database-strategy:
              standard:
                sharding-column: user_id
                sharding-algorithm-name: databaseInline
            table-strategy:
              standard:
                sharding-column: order_id
                sharding-algorithm-name: orderInline
            key-generate-strategy:
              column: order_id
              key-generator-name: snowflake

        sharding-algorithms:
          databaseInline:
            type: INLINE
            props:
              algorithm-expression: ds${user_id % 2}
          orderInline:
            type: INLINE
            props:
              algorithm-expression: t_order${order_id % 2}
          tableMy:
            type: My
        keyGenerators:
          snowflake:
            type: SNOWFLAKE
          atomic:
            type: ATOMIC
seata:
  enabled: true
  application:
    id: order
  tx-service-group: order-group
  service:
    vgroup-mapping:
      order-group: order-group
    order-group:
      grouplist: seata.kevin.com:31400
    enableDegrade: false
    disable: false

mybatis:
  configuration:
    map-underscore-to-caml-case: true
  type:
    handlers:
      package: com.kevin.sample.order.mapper.handler.EnumTypeHandler


logging:
  level:
    com.kevin.sample.order.mapper: debug







