spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # if set it as true, it will generate all services that already registered in nacos
          lowerCaseServiceId: true # 请求服务是小写的时候改成true（默认为false轻微服务必须是大写）
      routes:
        - id: order
          uri: lb://order # 服务端 service_id
          predicates:
            - Path=/** # same with set lacator.enable as true, but you can set more detail path for different proposals.
        - id: shopping
          uri: lb://shopping # 服务端 service_id
          predicates:
            - Path=/**